compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
deepspeed_config:
  deepspeed_multinode_launcher: standard
  gradient_accumulation_steps: 2
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero3_save_16bit_model: false
  zero_stage: 2
# distributed_type: DEEPSPEED 
downcast_bf16: 'fp16'
gpu_ids: '0,1,2,3'
machine_rank: 0
main_process_ip: 127.0.0.1 #主机ip
main_process_port: 10086  #端口
main_training_function: main
mixed_precision: 'fp16' #fp16 no等
num_machines: 1  #这个后面可以再配置启动命令中修改
num_processes: 4 # 这个指示的的是多机多卡的总卡数，而不是每台机器卡数，类似于ddp的rank
rdzv_backend: static
same_network: True
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false