# 实验名称
experiment: "CAN"

# 随机种子
seed: 20211024

# 训练参数
epochs: 240
batch_size: 20
workers: 0
best_score: 0.9
train_parts: 1
valid_parts: 1
valid_start: 0
save_start: 0

optimizer: Adadelta 
lr: 1
lr_decay: cosine
step_ratio: 10
step_decay: 5
eps: 1e-6
weight_decay: 1e-4
beta: 0.9

dropout: True
dropout_ratio: 0.5
relu: True
gradient: 100
gradient_clip: True
use_label_mask: False

# 训练数据
image_path: "/home/qiujin/data/priting_data/"
train_path: "/home/qiujin/data/priting_data/train.txt"
eval_path: "/home/qiujin/data/priting_data/val.txt"

train_image_path: "/home/qiujin/data/mix_data_v5/train.pkl"
train_label_path: "/home/qiujin/data/mix_data_v5/train.txt"

eval_image_path: "/home/qiujin/data/mix_data_v5/val.pkl"
eval_label_path: "/home/qiujin/data/mix_data_v5/val.txt"

word_path: "/home/qiujin/data/priting_data/dictory.txt"

# collate_fn
collate_fn: collate_fn

densenet:
  ratio: 16
  growthRate: 24
  reduction: 0.5
  bottleneck: True
  use_dropout: True

encoder:
  input_channel: 1
  out_channel: 684 

decoder:
  net: AttDecoder
  cell: 'GRU'
  input_size: 256
  hidden_size: 256

counting_decoder:
  in_channel: 684 # 684
  out_channel: 533 #208

attention:
  attention_dim: 512
  word_conv_kernel: 1

transformer:
  pad_idx: 0
  sos_idx: 1
  eos_idx: 2
  max_len: 200
  d_model: 256
  nhead: 8
  num_decoder_layers: 3
  dim_feedforward: 1024
  dropout: 0.3
  dc: 32
  cross_coverage: true
  self_coverage: true

attention_map_vis_path: 'vis/attention_map'
counting_map_vis_path: 'vis/counting_map'

whiten_type: None
max_step: 256

optimizer_save: False
finetune: True
checkpoint_dir: 'checkpoints'
checkpoint: "/home/qiujin/project/CAN_src/checkpoints/CAN_2024-03-26-14-28_decoder-AttDecoder/CAN_2024-03-26-14-28_decoder-AttDecoder_WordRate-0.9870_ExpRate-0.8820_115.pth"
log_dir: 'logs'
